/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arduinocontroller;
import static arduinocontroller.SerialTest.serialWrite;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Nick
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame()
    {
        initComponents();
        plant1StatusLabel.setForeground(Color.red);
        plant2StatusLabel.setForeground(Color.red);
        plant3StatusLabel.setForeground(Color.red);
        plant4StatusLabel.setForeground(Color.red);
        connectionStatusLabel.setForeground(Color.red);
    }
    public static SerialTest serialTest = new SerialTest();
    public static StringBuilder stringBuilder = new StringBuilder();
    public static boolean isLocked = true;
    
    public static void printStringToConsole(String s)
    {
        stringBuilder.append(s + "\n");
        serialMonitorPane.setText(stringBuilder.toString());
        //System.out.println(stringBuilder);
    }
    
    public static Variables variables = new Variables();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        plant1SetpointBox = new javax.swing.JComboBox<>();
        plant2SetpointBox = new javax.swing.JComboBox<>();
        plant3SetpointBox = new javax.swing.JComboBox<>();
        plant4SetpointBox = new javax.swing.JComboBox<>();
        consoleField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        plant1EndpointBox = new javax.swing.JComboBox<>();
        plant2EndpointBox = new javax.swing.JComboBox<>();
        plant3EndpointBox = new javax.swing.JComboBox<>();
        plant4EndpointBox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        plant1StatusLabel = new javax.swing.JLabel();
        plant2StatusLabel = new javax.swing.JLabel();
        plant4StatusLabel = new javax.swing.JLabel();
        plant3StatusLabel = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        plant1PercentLabel = new javax.swing.JLabel();
        plant2PercentLabel = new javax.swing.JLabel();
        plant3PercentLabel = new javax.swing.JLabel();
        plant4PercentLabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        plant1WaterStatus = new javax.swing.JLabel();
        plant2WaterStatus = new javax.swing.JLabel();
        plant3WaterStatus = new javax.swing.JLabel();
        plant4WaterStatus = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        plant1SetpointLabel = new javax.swing.JLabel();
        plant2SetpointLabel = new javax.swing.JLabel();
        plant3SetpointLabel = new javax.swing.JLabel();
        plant4SetpointLabel = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        plant4EndpointLabel = new javax.swing.JLabel();
        plant3EndpointLabel = new javax.swing.JLabel();
        plant2EndpointLabel = new javax.swing.JLabel();
        plant1EndpointLabel = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        connectionStatusLabel = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        comPortLabel = new javax.swing.JLabel();
        plant1StatusButton = new javax.swing.JButton();
        plant2StatusButton = new javax.swing.JButton();
        plant3StatusButton = new javax.swing.JButton();
        plant4StatusButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        serialMonitorPane = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        resyncMenuItem = new javax.swing.JMenuItem();
        connectMenuItem = new javax.swing.JMenuItem();
        disconnectMenuItem = new javax.swing.JMenuItem();
        manualControlButton = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        advancedModeBox = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Arduino Control Panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Set Plant 1 Status: ");
        jLabel2.setToolTipText("Toggles Between Enabled and Disabled For Plant 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Set Plant 2 Status: ");
        jLabel3.setToolTipText("Toggles Between Enabled and Disabled For Plant 2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Set Plant 3 Status: ");
        jLabel4.setToolTipText("Toggles Between Enabled and Disabled For Plant 3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Plant 1 Setpoint:");
        jLabel5.setToolTipText("Enables Pump And Solinoid 1 At This Setpoint");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Set Plant 4 Status: ");
        jLabel6.setToolTipText("Toggles Between Enabled and Disabled For Plant 4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Plant 2 Setpoint:");
        jLabel7.setToolTipText("Enables Pump And Solinoid 2 At This Setpoint");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Plant 3 Setpoint:");
        jLabel8.setToolTipText("Enables Pump And Solinoid 3 At This Setpoint");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Plant 4 Setpoint:");
        jLabel10.setToolTipText("Enables Pump And Solinoid 4 At This Setpoint");

        plant1SetpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant1SetpointBox.setToolTipText("Enables Pump And Solinoid 1 At This Setpoint");
        plant1SetpointBox.setEnabled(false);
        plant1SetpointBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                plant1SetpointBoxItemStateChanged(evt);
            }
        });
        plant1SetpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant1SetpointBoxActionPerformed(evt);
            }
        });

        plant2SetpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant2SetpointBox.setToolTipText("Enables Pump And Solinoid 2 At This Setpoint");
        plant2SetpointBox.setEnabled(false);
        plant2SetpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant2SetpointBoxActionPerformed(evt);
            }
        });

        plant3SetpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant3SetpointBox.setToolTipText("Enables Pump And Solinoid 3 At This Setpoint");
        plant3SetpointBox.setEnabled(false);
        plant3SetpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant3SetpointBoxActionPerformed(evt);
            }
        });

        plant4SetpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant4SetpointBox.setToolTipText("Enables Pump And Solinoid 4 At This Setpoint");
        plant4SetpointBox.setEnabled(false);
        plant4SetpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant4SetpointBoxActionPerformed(evt);
            }
        });

        consoleField.setEnabled(false);
        consoleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleFieldActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.setEnabled(false);
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Plant 1 Endpoint:");
        jLabel11.setToolTipText("Disables Pump And Solinoid 1 At This Setpoint");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Plant 2 Endpoint:");
        jLabel12.setToolTipText("Diables Pump And Solinoid 2 At This Setpoint");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Plant 3 Endpoint:");
        jLabel13.setToolTipText("Diables Pump And Solinoid 3 At This Setpoint");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Plant 4 Endpoint:");
        jLabel14.setToolTipText("Diables Pump And Solinoid 4 At This Setpoint");

        plant1EndpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant1EndpointBox.setToolTipText("Disables Pump And Solinoid 1 At This Setpoint");
        plant1EndpointBox.setEnabled(false);
        plant1EndpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant1EndpointBoxActionPerformed(evt);
            }
        });

        plant2EndpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant2EndpointBox.setToolTipText("Diables Pump And Solinoid 2 At This Setpoint");
        plant2EndpointBox.setEnabled(false);
        plant2EndpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant2EndpointBoxActionPerformed(evt);
            }
        });

        plant3EndpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant3EndpointBox.setToolTipText("Diables Pump And Solinoid 3 At This Setpoint");
        plant3EndpointBox.setEnabled(false);
        plant3EndpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant3EndpointBoxActionPerformed(evt);
            }
        });

        plant4EndpointBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100" }));
        plant4EndpointBox.setToolTipText("Diables Pump And Solinoid 4 At This Setpoint");
        plant4EndpointBox.setEnabled(false);
        plant4EndpointBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant4EndpointBoxActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Status Monitor");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Plant 1:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Plant 2:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Plant 3:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Plant 4:");

        plant1StatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant1StatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant1StatusLabel.setText("Inactive");

        plant2StatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant2StatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant2StatusLabel.setText("Inactive");

        plant4StatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant4StatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant4StatusLabel.setText("Inactive");

        plant3StatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant3StatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant3StatusLabel.setText("Inactive");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Plant 1 Percentage:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Plant 2 Percentage:");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Plant 3 Percentage:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Plant 4 Percentage:");

        plant1PercentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant1PercentLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant1PercentLabel.setText("0%");

        plant2PercentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant2PercentLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant2PercentLabel.setText("0%");

        plant3PercentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant3PercentLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant3PercentLabel.setText("0%");

        plant4PercentLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant4PercentLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant4PercentLabel.setText("0%");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Plant 1 Status:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Plant 2 Status:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Plant 3 Status:");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Plant 4 Status:");

        plant1WaterStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant1WaterStatus.setForeground(new java.awt.Color(255, 255, 255));
        plant1WaterStatus.setText("Waiting");

        plant2WaterStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant2WaterStatus.setForeground(new java.awt.Color(255, 255, 255));
        plant2WaterStatus.setText("Waiting");

        plant3WaterStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant3WaterStatus.setForeground(new java.awt.Color(255, 255, 255));
        plant3WaterStatus.setText("Waiting");

        plant4WaterStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant4WaterStatus.setForeground(new java.awt.Color(255, 255, 255));
        plant4WaterStatus.setText("Waiting");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Plant 4 Setpoint:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Plant 3 Setpoint:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Plant 2 Setpoint:");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Plant 1 Setpoint:");

        plant1SetpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant1SetpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant1SetpointLabel.setText("0%");

        plant2SetpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant2SetpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant2SetpointLabel.setText("0%");

        plant3SetpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant3SetpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant3SetpointLabel.setText("0%");

        plant4SetpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant4SetpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant4SetpointLabel.setText("0%");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Plant 1 Endpoint:");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Plant 2 Endpoint:");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Plant 3 Endpoint:");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Plant 4 Endpoint:");

        plant4EndpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant4EndpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant4EndpointLabel.setText("0%");

        plant3EndpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant3EndpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant3EndpointLabel.setText("0%");

        plant2EndpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant2EndpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant2EndpointLabel.setText("0%");

        plant1EndpointLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        plant1EndpointLabel.setForeground(new java.awt.Color(255, 255, 255));
        plant1EndpointLabel.setText("0%");

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Connection Status:");

        connectionStatusLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        connectionStatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        connectionStatusLabel.setText("Disconnected");

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("COMM Port Assigned:");

        comPortLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comPortLabel.setForeground(new java.awt.Color(255, 255, 255));
        comPortLabel.setText("N/A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(plant4StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(plant1StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plant2StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plant3StatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(plant1PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(plant2PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plant3PercentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(plant4PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plant3WaterStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(plant2WaterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(plant1WaterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plant4WaterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel42)))
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plant2SetpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plant1SetpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plant3SetpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plant4SetpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant2EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant3EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant1EndpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plant4EndpointLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connectionStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comPortLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant1SetpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant2SetpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant3SetpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant4SetpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant1StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant1PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant1WaterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel48, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant1EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(connectionStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant2StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant2PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant2WaterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel49, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant2EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comPortLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant3StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant3PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant3WaterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel50, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant3EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant4StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant4PercentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant4WaterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plant4EndpointLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        plant1StatusButton.setText("Disabled");
        plant1StatusButton.setEnabled(false);
        plant1StatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant1StatusButtonActionPerformed(evt);
            }
        });

        plant2StatusButton.setText("Disabled");
        plant2StatusButton.setEnabled(false);
        plant2StatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant2StatusButtonActionPerformed(evt);
            }
        });

        plant3StatusButton.setText("Disabled");
        plant3StatusButton.setEnabled(false);
        plant3StatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant3StatusButtonActionPerformed(evt);
            }
        });

        plant4StatusButton.setText("Disabled");
        plant4StatusButton.setEnabled(false);
        plant4StatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plant4StatusButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.setEnabled(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        serialMonitorPane.setEditable(false);
        serialMonitorPane.setColumns(20);
        serialMonitorPane.setLineWrap(true);
        serialMonitorPane.setRows(5);
        serialMonitorPane.setWrapStyleWord(true);
        jScrollPane2.setViewportView(serialMonitorPane);

        jMenu1.setText("File");

        resyncMenuItem.setText("Re-Sync Data");
        resyncMenuItem.setEnabled(false);
        resyncMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resyncMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(resyncMenuItem);

        connectMenuItem.setText("Connect To Board");
        connectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(connectMenuItem);

        disconnectMenuItem.setText("Disconnect From Board");
        disconnectMenuItem.setEnabled(false);
        disconnectMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(disconnectMenuItem);

        manualControlButton.setText("Maual Control");
        manualControlButton.setEnabled(false);
        manualControlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualControlButtonActionPerformed(evt);
            }
        });
        jMenu1.add(manualControlButton);

        jMenuItem4.setText("About");
        jMenuItem4.setEnabled(false);
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Quit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");
        jMenu2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenu2ItemStateChanged(evt);
            }
        });

        jMenuItem6.setText("Command List/Help");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        advancedModeBox.setText("Advanced Display");
        advancedModeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedModeBoxActionPerformed(evt);
            }
        });
        jMenu2.add(advancedModeBox);

        jMenuItem1.setText("Show Graph");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Lock/Unlock Controlls");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant3StatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant4StatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant1SetpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant2SetpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant3SetpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant4SetpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant1EndpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant2EndpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant3EndpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plant4EndpointBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plant1StatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(plant2StatusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consoleField, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2))
                            .addComponent(plant1StatusButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3))
                            .addComponent(plant2StatusButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4))
                            .addComponent(plant3StatusButton))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel6))
                            .addComponent(plant4StatusButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(plant1SetpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(plant2SetpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(plant3SetpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(plant4SetpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(plant1EndpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(plant2EndpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(plant3EndpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(plant4EndpointBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consoleField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sendButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void plant1StatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant1StatusButtonActionPerformed
       
        
        Variables.plant1StatusBoolean = !Variables.plant1StatusBoolean;
        
        if(Variables.isPlant1StatusBoolean() == true)
        {
            plant1StatusButton.setText("Enabled");
            plant1StatusLabel.setText("Active");
            plant1StatusLabel.setForeground(Color.green);
            serialWrite("[SEND]isPlant1Enabled=1");
            MainFrame.printStringToConsole("[INFO]Plant 1 Enabled");
        }
        else
        {
            plant1StatusButton.setText("Disabled");
            plant1StatusLabel.setText("Inactive");
            plant1StatusLabel.setForeground(Color.red);
            serialWrite("[SEND]isPlant1Enabled=0");
            MainFrame.printStringToConsole("[INFO]Plant 1 Disabled");
        }
        
    }//GEN-LAST:event_plant1StatusButtonActionPerformed

    private void plant2StatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant2StatusButtonActionPerformed
        
        Variables.plant2StatusBoolean = !Variables.plant2StatusBoolean;
        
        if(Variables.isPlant2StatusBoolean() == true)
        {
            plant2StatusButton.setText("Enabled");
            plant2StatusLabel.setText("Active");
            plant2StatusLabel.setForeground(Color.green);
            serialWrite("[SEND]isPlant2Enabled=1");
            MainFrame.printStringToConsole("[INFO]Plant 2 Enabled");
        }
        else
        {
            plant2StatusButton.setText("Disabled");
            plant2StatusLabel.setText("Inactive");
            plant2StatusLabel.setForeground(Color.red);
            serialWrite("[SEND]isPlant2Enabled=0");
            MainFrame.printStringToConsole("[INFO]Plant 2 Disabled");
        }
    }//GEN-LAST:event_plant2StatusButtonActionPerformed

    private void plant3StatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant3StatusButtonActionPerformed
       
        Variables.plant3StatusBoolean = !Variables.plant3StatusBoolean;
        
        if(Variables.isPlant3StatusBoolean() == true)
        {
            plant3StatusButton.setText("Enabled");
            plant3StatusLabel.setText("Active");
            plant3StatusLabel.setForeground(Color.green);
            serialWrite("[SEND]isPlant3Enabled=1");
            MainFrame.printStringToConsole("[INFO]Plant 3 Enabled");
        }
        else
        {
            plant3StatusButton.setText("Disabled");
            plant3StatusLabel.setText("Inactive");
            plant3StatusLabel.setForeground(Color.red);
            serialWrite("[SEND]isPlant3Enabled=0");
            MainFrame.printStringToConsole("[INFO]Plant 3 Disabled");
        }
    }//GEN-LAST:event_plant3StatusButtonActionPerformed

    
    private void plant4StatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant4StatusButtonActionPerformed
        
        Variables.plant4StatusBoolean = !Variables.plant4StatusBoolean;
        
        if(Variables.isPlant4StatusBoolean() == true)
        {
            plant4StatusButton.setText("Enabled");
            plant4StatusLabel.setText("Active");
            plant4StatusLabel.setForeground(Color.green);
            serialWrite("[SEND]isPlant4Enabled=1");
            MainFrame.printStringToConsole("[INFO]Plant 4 Enabled");
        }
        else
        {
            plant4StatusButton.setText("Disabled");
            plant4StatusLabel.setText("Inactive");
            plant4StatusLabel.setForeground(Color.red);
            serialWrite("[SEND]isPlant4Enabled=0");
            MainFrame.printStringToConsole("[INFO]Plant 4 Disabled");
        }
    }//GEN-LAST:event_plant4StatusButtonActionPerformed

    private void plant1SetpointBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_plant1SetpointBoxItemStateChanged
        
        Variables.plant1SetpointInt = Integer.parseInt(plant1SetpointBox.getSelectedItem().toString());
        plant1SetpointLabel.setText(Variables.plant1SetpointInt + "%");
        SerialTest.serialWrite("[SEND]plant1SetpointInt=" + Variables.plant1SetpointInt);
    }//GEN-LAST:event_plant1SetpointBoxItemStateChanged

    private void plant2SetpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant2SetpointBoxActionPerformed
        
        Variables.plant2SetpointInt = Integer.parseInt(plant2SetpointBox.getSelectedItem().toString());
        plant2SetpointLabel.setText(Variables.plant2SetpointInt + "%");
        SerialTest.serialWrite("[SEND]plant2SetpointInt=" + Variables.plant2SetpointInt);
    }//GEN-LAST:event_plant2SetpointBoxActionPerformed

    private void plant3SetpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant3SetpointBoxActionPerformed
        
        Variables.plant3SetpointInt = Integer.parseInt(plant3SetpointBox.getSelectedItem().toString());
        plant3SetpointLabel.setText(Variables.plant3SetpointInt + "%");
        SerialTest.serialWrite("[SEND]plant3SetpointInt=" + Variables.plant3SetpointInt);
    }//GEN-LAST:event_plant3SetpointBoxActionPerformed

    private void plant4SetpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant4SetpointBoxActionPerformed
        
        Variables.plant4SetpointInt = Integer.parseInt(plant4SetpointBox.getSelectedItem().toString());
        plant4SetpointLabel.setText(Variables.plant4SetpointInt + "%");
        SerialTest.serialWrite("[SEND]plant4SetpointInt=" + Variables.plant4SetpointInt);
    }//GEN-LAST:event_plant4SetpointBoxActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        String s = "";
        s = consoleField.getText();
        serialWrite(s);
        printStringToConsole("[Console] " + s);
        consoleField.setText("");
        
    }//GEN-LAST:event_sendButtonActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void plant1EndpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant1EndpointBoxActionPerformed
        
        Variables.plant1EndpointInt = Integer.parseInt(plant1EndpointBox.getSelectedItem().toString());
        plant1EndpointLabel.setText(Variables.plant1EndpointInt + "%");
        SerialTest.serialWrite("[SEND]plant1EndpointInt=" + Variables.plant1EndpointInt);
    }//GEN-LAST:event_plant1EndpointBoxActionPerformed

    private void plant2EndpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant2EndpointBoxActionPerformed
        
        Variables.plant2EndpointInt = Integer.parseInt(plant2EndpointBox.getSelectedItem().toString());
        plant2EndpointLabel.setText(Variables.plant2EndpointInt + "%");
        SerialTest.serialWrite("[SEND]plant2EndpointInt=" + Variables.plant2EndpointInt);
    }//GEN-LAST:event_plant2EndpointBoxActionPerformed

    private void plant3EndpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant3EndpointBoxActionPerformed
        
        Variables.plant3EndpointInt = Integer.parseInt(plant3EndpointBox.getSelectedItem().toString());
        plant3EndpointLabel.setText(Variables.plant3EndpointInt + "%");
        SerialTest.serialWrite("[SEND]plant3EndpointInt=" + Variables.plant3EndpointInt);
    }//GEN-LAST:event_plant3EndpointBoxActionPerformed

    private void plant4EndpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant4EndpointBoxActionPerformed
        
        Variables.plant4EndpointInt = Integer.parseInt(plant4EndpointBox.getSelectedItem().toString());
        plant4EndpointLabel.setText(Variables.plant4EndpointInt + "%");
        SerialTest.serialWrite("[SEND]plant4EndpointInt=" + Variables.plant4EndpointInt);
    }//GEN-LAST:event_plant4EndpointBoxActionPerformed

    private void connectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectMenuItemActionPerformed
        
        
        try
        {
            SerialTest.start();
        } 
        catch (Exception ex)
        {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_connectMenuItemActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        
        stringBuilder.delete(0, stringBuilder.length());
        serialMonitorPane.setText(stringBuilder.toString());
    }//GEN-LAST:event_clearButtonActionPerformed

    private void manualControlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualControlButtonActionPerformed
        
       ManualControl manualControl = new ManualControl();
       manualControl.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       manualControl.setTitle("Manual Control Window");
       manualControl.setVisible(true);
    }//GEN-LAST:event_manualControlButtonActionPerformed

    private void plant1SetpointBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plant1SetpointBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plant1SetpointBoxActionPerformed

    private void consoleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleFieldActionPerformed
        
        String s = "";
        s = consoleField.getText();
        serialWrite(s);
        printStringToConsole("[Console] " + s);
        consoleField.setText("");
    }//GEN-LAST:event_consoleFieldActionPerformed

    private void resyncMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resyncMenuItemActionPerformed
        
        serialWrite("connected");
    }//GEN-LAST:event_resyncMenuItemActionPerformed

    private void disconnectMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectMenuItemActionPerformed

        SerialTest serialTest = new SerialTest();
        SerialTest.disconnectFromDevice();
    }//GEN-LAST:event_disconnectMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CommandsWindow commandsWindow = new CommandsWindow();
        commandsWindow.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        commandsWindow.setTitle("Commands and Help");
        commandsWindow.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenu2ItemStateChanged

    }//GEN-LAST:event_jMenu2ItemStateChanged

    private void advancedModeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedModeBoxActionPerformed
        // TODO add your handling code here:
        Variables.advancedDiagnostics = !Variables.advancedDiagnostics;
        if(Variables.advancedDiagnostics == true)
        {
            SerialTest.handleStrings("[INFO] Advanced Debugging Enabled For This Session.");
            SerialTest.handleStrings("[INFO] StackTrace Will Be Printed To The Console.");
        }
        else if(Variables.advancedDiagnostics == false)
        {
            SerialTest.handleStrings("[INFO] Advanced Debugging Disabled.");
        }
    }//GEN-LAST:event_advancedModeBoxActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            
      //LineChartDisplay lineChart = new LineChartDisplay();
      //lineChart.start();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        if(SerialTest.canWrite)
        {
            isLocked = !isLocked;
        }
        if(isLocked && SerialTest.canWrite)
        {
            clearButton.setEnabled(true);
            sendButton.setEnabled(true);
            consoleField.setEnabled(true);

            plant1EndpointBox.setEnabled(true);
            plant1SetpointBox.setEnabled(true);
            plant1StatusButton.setEnabled(true);

            plant2EndpointBox.setEnabled(true);
            plant2SetpointBox.setEnabled(true);
            plant2StatusButton.setEnabled(true);

            plant3EndpointBox.setEnabled(true);
            plant3SetpointBox.setEnabled(true);
            plant3StatusButton.setEnabled(true);

            plant4EndpointBox.setEnabled(true);
            plant4SetpointBox.setEnabled(true);
            plant4StatusButton.setEnabled(true);
        }
        else
        {
            clearButton.setEnabled(false);
            sendButton.setEnabled(false);
            consoleField.setEnabled(false);

            plant1EndpointBox.setEnabled(false);
            plant1SetpointBox.setEnabled(false);
            plant1StatusButton.setEnabled(false);

            plant2EndpointBox.setEnabled(false);
            plant2SetpointBox.setEnabled(false);
            plant2StatusButton.setEnabled(false);

            plant3EndpointBox.setEnabled(false);
            plant3SetpointBox.setEnabled(false);
            plant3StatusButton.setEnabled(false);

            plant4EndpointBox.setEnabled(false);
            plant4SetpointBox.setEnabled(false);
            plant4StatusButton.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     *         variables.advancedDiagnostics = advancedModeBox.isSelected();
        if(advancedModeBox.isSelected() == true)
        {
            serialTest.handleStrings("[INFO] Advanced Debugging Enabled For This Session.");
            serialTest.handleStrings("[INFO] StackTrace Will Be Printed To The Console.");
        }
        else if(advancedModeBox.isSelected() == false)
        {
            serialTest.handleStrings("[INFO] Advanced Debugging Disabled.");
        }
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem advancedModeBox;
    public static javax.swing.JButton clearButton;
    public static javax.swing.JLabel comPortLabel;
    public static javax.swing.JMenuItem connectMenuItem;
    public static javax.swing.JLabel connectionStatusLabel;
    public static javax.swing.JTextField consoleField;
    public static javax.swing.JMenuItem disconnectMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JMenuItem manualControlButton;
    public static javax.swing.JComboBox<String> plant1EndpointBox;
    public static javax.swing.JLabel plant1EndpointLabel;
    public static javax.swing.JLabel plant1PercentLabel;
    public static javax.swing.JComboBox<String> plant1SetpointBox;
    public static javax.swing.JLabel plant1SetpointLabel;
    public static javax.swing.JButton plant1StatusButton;
    public static javax.swing.JLabel plant1StatusLabel;
    public static javax.swing.JLabel plant1WaterStatus;
    public static javax.swing.JComboBox<String> plant2EndpointBox;
    public static javax.swing.JLabel plant2EndpointLabel;
    public static javax.swing.JLabel plant2PercentLabel;
    public static javax.swing.JComboBox<String> plant2SetpointBox;
    public static javax.swing.JLabel plant2SetpointLabel;
    public static javax.swing.JButton plant2StatusButton;
    public static javax.swing.JLabel plant2StatusLabel;
    public static javax.swing.JLabel plant2WaterStatus;
    public static javax.swing.JComboBox<String> plant3EndpointBox;
    public static javax.swing.JLabel plant3EndpointLabel;
    public static javax.swing.JLabel plant3PercentLabel;
    public static javax.swing.JComboBox<String> plant3SetpointBox;
    public static javax.swing.JLabel plant3SetpointLabel;
    public static javax.swing.JButton plant3StatusButton;
    public static javax.swing.JLabel plant3StatusLabel;
    public static javax.swing.JLabel plant3WaterStatus;
    public static javax.swing.JComboBox<String> plant4EndpointBox;
    public static javax.swing.JLabel plant4EndpointLabel;
    public static javax.swing.JLabel plant4PercentLabel;
    public static javax.swing.JComboBox<String> plant4SetpointBox;
    public static javax.swing.JLabel plant4SetpointLabel;
    public static javax.swing.JButton plant4StatusButton;
    public static javax.swing.JLabel plant4StatusLabel;
    public static javax.swing.JLabel plant4WaterStatus;
    public static javax.swing.JMenuItem resyncMenuItem;
    public static javax.swing.JButton sendButton;
    public static javax.swing.JTextArea serialMonitorPane;
    // End of variables declaration//GEN-END:variables
}
